# debug = true

# skip_platforms = [
#     "linux/mips64",
#     "linux/ppc64le",
#     "linux/riscv64",
#     "linux/s390x",
# ]

# dockerfile = "Dockerfile"

# jobs_limit = 4

# buildx_args = []

# directory = "."
