# debug = true

platforms = [
    "linux/386",
    "linux/amd64",
    "linux/amd64/v2",
    "linux/arm/v6",
    "linux/arm/v7",
    "linux/arm64",
    "linux/ppc64le",
    "linux/riscv64",
    "linux/s390x",
]

# load_platform = "linux/amd64"

# directory = "."

# dockerfile = "Dockerfile"

# jobs_limit = 4

# buildx_args = []
